# Generated by Django 4.2.4 on 2023-11-24 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelSchedule',
            fields=[
                ('pk_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('pass_day', models.IntegerField()),
                ('preparation_cost', models.IntegerField(null=True)),
                ('real_cost', models.IntegerField(null=True)),
                ('memo', models.CharField(max_length=512)),
                ('isdelete', models.CharField(default='N', max_length=1)),
                ('delete_dt', models.DateTimeField(blank=True, null=True)),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update_dt', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TravelDayIntroduce',
            fields=[
                ('pk_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('schedule_pk_id', models.CharField(max_length=32)),
                ('schedule_list', models.JSONField()),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('hotel_name', models.CharField(max_length=128, null=True)),
                ('hotel_map_location', models.CharField(max_length=2048, null=True)),
                ('shopping_list', models.JSONField()),
                ('memo_list', models.JSONField()),
                ('breakfirst', models.CharField(max_length=128, null=True)),
                ('breakfirst_map_location', models.CharField(max_length=2048, null=True)),
                ('launch', models.CharField(max_length=128, null=True)),
                ('launch_map_location', models.CharField(max_length=2048, null=True)),
                ('dinner', models.CharField(max_length=128, null=True)),
                ('dinner_map_location', models.CharField(max_length=2048, null=True)),
                ('isdelete', models.CharField(default='N', max_length=1)),
                ('delete_dt', models.DateTimeField(blank=True, null=True)),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update_dt', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=0)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_introduces', to='travel.travelschedule')),
            ],
        ),
        migrations.CreateModel(
            name='TravelCostRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=512)),
                ('memo', models.CharField(max_length=1024)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency_type', models.CharField(default='TWD', max_length=16)),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=1, max_digits=15)),
                ('final_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_records', to='travel.travelschedule')),
            ],
        ),
    ]
