# Generated by Django 4.2.4 on 2023-11-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TravelCostRecord',
            new_name='cost_record',
        ),
        migrations.RenameModel(
            old_name='TravelDayIntroduce',
            new_name='day_introduce',
        ),
        migrations.RenameModel(
            old_name='TravelSchedule',
            new_name='schedule',
        ),
    ]
