# Generated by Django 4.2.4 on 2023-11-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_rename_travelcostrecord_cost_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost_record',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='day_introduce',
            name='schedule',
        ),
    ]
