# Generated by Django 4.2.4 on 2023-11-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_day_introduce_ser_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='user_pk_id',
            field=models.CharField(default=123, max_length=32),
            preserve_default=False,
        ),
    ]
