# Generated by Django 4.2.4 on 2023-11-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_schedule_user_pk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_record',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='cost_record',
            name='currency_type',
            field=models.CharField(default='TWD', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='cost_record',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='cost_record',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='cost_record',
            name='final_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='cost_record',
            name='memo',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='cost_record',
            name='type',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='day_introduce',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='day_introduce',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='day_introduce',
            name='memo_list',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='day_introduce',
            name='schedule_list',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='day_introduce',
            name='ser_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='day_introduce',
            name='shopping_list',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='day_introduce',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='day_introduce',
            name='version',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
