# Generated by Django 4.2.4 on 2023-12-03 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_remove_cost_record_id_cost_record_pk_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost_record',
            name='memo',
        ),
    ]
