# Generated by Django 4.2.4 on 2023-12-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_remove_cost_record_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='real_cost',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
