# Generated by Django 4.2.4 on 2023-12-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_alter_schedule_real_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost_record',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cost_record',
            name='delete_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cost_record',
            name='isdelete',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='cost_record',
            name='last_update_dt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cost_record',
            name='version',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
