# Generated by Django 4.2.4 on 2023-12-03 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_cost_record_create_dt_cost_record_delete_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_record',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='day_introduce',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
