# Generated by Django 4.2.4 on 2023-12-09 07:48

from django.db import migrations, models
import travel.models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_alter_cost_record_create_dt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploaded_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=travel.models.getUploadPath)),
            ],
        )      
    ]
