# Generated by Django 4.2.4 on 2023-12-09 08:55

import common
from django.db import migrations, models

from travel.models import getUploadPath


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_delete_uploaded_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploaded_file',
            fields=[
                ('pk_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=getUploadPath)),
                ('file_size', models.IntegerField()),
                ('file_ext', models.CharField(max_length=16)),
                ('user_pk_id', models.CharField(max_length=32, null=True)),
                ('schedule_pk_id', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
