# Generated by Django 4.2.4 on 2023-12-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_uploaded_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploaded_file',
            old_name='file',
            new_name='file_name',
        ),
    ]
