# Generated by Django 4.2.4 on 2023-12-13 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0022_uploaded_file_create_dt_uploaded_file_delete_dt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule_uploaded_file',
            fields=[
                ('pk_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=1024)),
                ('file_ext', models.CharField(max_length=16)),
                ('file_size', models.IntegerField()),
                ('user_pk_id', models.CharField(max_length=32, null=True)),
                ('schedule_pk_id', models.CharField(max_length=32, null=True)),
                ('isdelete', models.CharField(default='N', max_length=1)),
                ('delete_dt', models.DateTimeField(blank=True, null=True)),
                ('create_dt', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('last_update_dt', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='uploaded_file',
            name='delete_dt',
        ),
        migrations.RemoveField(
            model_name='uploaded_file',
            name='schedule_pk_id',
        ),
        migrations.RemoveField(
            model_name='uploaded_file',
            name='user_pk_id',
        ),
    ]
