# Generated by Django 4.2.4 on 2023-12-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0023_schedule_uploaded_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaded_file',
            name='file_ext',
        ),
        migrations.RemoveField(
            model_name='uploaded_file',
            name='file_size',
        ),
    ]
