# Generated by Django 4.2.4 on 2023-12-13 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0024_remove_uploaded_file_file_ext_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule_file',
            fields=[
                ('pk_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('file_pk_id', models.CharField(max_length=32)),
                ('file_name', models.CharField(max_length=1024)),
                ('user_pk_id', models.CharField(max_length=32, null=True)),
                ('schedule_pk_id', models.CharField(max_length=32, null=True)),
                ('isdelete', models.CharField(default='N', max_length=1)),
                ('delete_dt', models.DateTimeField(blank=True, null=True)),
                ('create_dt', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('last_update_dt', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='schedule_uploaded_file',
        ),
    ]
