# Generated by Django 4.2.4 on 2023-12-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0025_schedule_file_delete_schedule_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_file',
            name='file_type',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
    ]
