# Generated by Django 4.2.4 on 2023-12-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0026_schedule_file_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded_file',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
