# Generated by Django 4.2.4 on 2023-12-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0027_uploaded_file_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded_file',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='uploaded_file',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
