# Generated by Django 4.2.4 on 2023-12-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0028_uploaded_file_height_uploaded_file_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_file',
            name='ser_no',
            field=models.IntegerField(null=True),
        ),
    ]
