# Generated by Django 4.2.4 on 2023-12-25 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0032_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_record',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 25, 13, 21, 3, 51104, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='cost_record',
            name='last_update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 25, 13, 21, 3, 51104, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='day_introduce',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 25, 13, 21, 3, 50104, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='day_introduce',
            name='last_update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 25, 13, 21, 3, 50104, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='schedule_file',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 25, 13, 21, 3, 51104, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='schedule_file',
            name='last_update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 25, 13, 21, 3, 51104, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_file',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 25, 13, 21, 3, 51104, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_file',
            name='last_update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 25, 13, 21, 3, 51104, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
