# Generated by Django 4.2.4 on 2023-09-09 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('pk_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('user_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('isdelete', models.CharField(default='N', max_length=1)),
                ('delete_dt', models.DateTimeField(blank=True, null=True)),
                ('create_dt', models.DateTimeField(blank=True, null=True)),
                ('last_update_dt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Planning',
            fields=[
                ('pk_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('user_pk_id', models.CharField(max_length=32)),
                ('planning_name', models.CharField(max_length=126)),
                ('planning_description', models.CharField(max_length=1024)),
                ('planning_start_dt', models.DateTimeField()),
                ('planning_end_dt', models.DateTimeField()),
                ('isdelete', models.CharField(default='N', max_length=1)),
                ('delete_dt', models.DateTimeField(blank=True, null=True)),
                ('create_dt', models.DateTimeField(blank=True, null=True)),
                ('last_update_dt', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='tsp.user')),
            ],
        ),
    ]
