# Generated by Django 4.2.4 on 2023-09-09 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Planning_Place',
            fields=[
                ('user_planning_pk_id', models.CharField(max_length=32)),
                ('pk_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=126)),
                ('place_description', models.CharField(max_length=2048, null=True)),
                ('place_location_name', models.CharField(max_length=512)),
                ('lat', models.CharField(max_length=126)),
                ('lng', models.CharField(max_length=126)),
                ('memo', models.JSONField()),
                ('isdelete', models.CharField(default='N', max_length=1)),
                ('delete_dt', models.DateTimeField(blank=True, null=True)),
                ('create_dt', models.DateTimeField(blank=True, null=True)),
                ('last_update_dt', models.DateTimeField(auto_now=True, null=True)),
                ('user_planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_planning', to='tsp.user_planning')),
            ],
        ),
    ]
