# Generated by Django 4.2.4 on 2023-09-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsp', '0002_user_planning_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_dt',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_planning_place',
            name='memo',
            field=models.CharField(),
        ),
    ]
