# Generated by Django 4.2.4 on 2023-09-09 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsp', '0006_alter_user_create_dt_alter_user_planning_create_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 9, 12, 24, 33, 960397, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='user_planning',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 9, 12, 24, 33, 990114, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='user_planning_place',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 9, 12, 24, 33, 990114, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
