# Generated by Django 4.2.4 on 2023-09-09 12:29

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tsp', '0007_alter_user_create_dt_alter_user_planning_create_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user_planning',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 9, 12, 29, 29, 615883, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='user_planning_place',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 9, 12, 29, 29, 615883, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
