# Generated by Django 4.2.4 on 2023-09-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsp', '0009_alter_user_create_dt_alter_user_planning_create_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_planning',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_planning_place',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_planning',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_planning_place',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
