# Generated by Django 4.2.4 on 2023-09-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsp', '0012_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
