# Generated by Django 4.2.4 on 2023-09-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsp', '0013_rename_user_name_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
