# Generated by Django 4.2.4 on 2023-09-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('pk_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('age', models.DecimalField(decimal_places=2, max_digits=4)),
                ('memo', models.CharField(blank=True, max_length=512, null=True)),
                ('isdelete', models.CharField(default='N', max_length=1)),
                ('delete_dt', models.DateTimeField(blank=True, null=True)),
                ('create_dt', models.DateTimeField(blank=True, null=True)),
                ('last_update_dt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
