# Generated by Django 4.2.4 on 2023-09-04 06:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_member_create_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=64),
        ),
        migrations.CreateModel(
            name='MemberOrder',
            fields=[
                ('pk_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('order_name', models.CharField(max_length=126)),
                ('order_detail', models.CharField(max_length=512)),
                ('order_amout', models.IntegerField(default=0)),
                ('order_price', models.IntegerField(default=0)),
                ('order_total_price', models.IntegerField(default=0)),
                ('isdelete', models.CharField(default='N', max_length=1)),
                ('delete_dt', models.DateTimeField(blank=True, null=True)),
                ('create_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('last_update_dt', models.DateTimeField(auto_now=True, null=True)),
                ('memeber_pk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.member')),
            ],
        ),
    ]
