# Generated by Django 4.2.4 on 2023-09-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_member_email_memberorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberOrder',
            new_name='Member_Order',
        ),
    ]
