# Generated by Django 4.2.4 on 2023-09-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_memberorder_member_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_order',
            name='memo',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
