# Generated by Django 4.2.4 on 2023-09-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_member_age_alter_member_create_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_order',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
